"""The order-API contract a single-symbol Strategy depends on (`self._engine`).

A `Strategy` is run either against a real `SingleSymbolEngine` (standalone single-symbol backtest) or a
`SymbolEngineShim` (one symbol of a shared-cash portfolio backtest). Both MUST expose the same
Strategy-facing surface, or a strategy that uses a method only one of them has breaks silently in the
other mode. This Protocol names that surface so the conformance test (and any type checker) catches
drift — the shim no longer mirrors the engine by hand on hope alone.
"""

from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class StrategyEngine(Protocol):
    """Everything a single-symbol `Strategy` calls on `self._engine`."""

    @property
    def position(self): ...
    @property
    def now(self) -> int: ...
    def equity_now(self) -> float: ...
    def drawdown_now(self) -> float: ...
    # market / target orders
    def submit(self, side_sign: int, size: float, weight: float = ..., stop=...) -> None: ...
    def submit_close(self) -> None: ...
    def order_target(self, target: float) -> None: ...
    def order_target_value(self, value: float) -> None: ...
    def order_target_percent(self, pct: float) -> None: ...
    # resting orders
    def submit_limit(self, side_sign: int, size: float, price: float, weight: float = ...) -> None: ...
    def submit_stop(self, side_sign: int, size: float, price: float, weight: float = ...) -> None: ...
    def submit_trailing(self, side_sign: int, size: float, trail: float, weight: float = ...) -> None: ...
    def submit_market_close(self, side_sign: int, size: float) -> None: ...
    def submit_limit_close(self, side_sign: int, size: float, price: float) -> None: ...
    def cancel_all(self) -> None: ...
    # multi-timeframe reads
    def bars_for(self, tf: str): ...
    def forming_for(self, tf: str): ...
