"""AI service layer — pure, JSON-friendly wrappers over the engine/optimizer/overfit code.

These functions are designed to be called by an MCP server or CLI chat interface.
All inputs and outputs are plain Python types (dicts, lists, floats, ints, strings)
so they serialize cleanly to JSON without any additional transformation.
"""

from __future__ import annotations

import numpy as np

from ..core.model import Bar
from ..core.vectorized import _sma_matrix, _cross_signals, sweep_sma_cross
from ..core.fastsim import fast_backtest
from ..analysis import metrics as _metrics
from ..analysis.overfit import deflated_sharpe_ratio, pbo_cscv, overfit_verdict
from ..data.cache import get_bars


# ---------------------------------------------------------------------------
# Task 1: bars_to_data + fetch_ohlcv
# ---------------------------------------------------------------------------


def bars_to_data(bars: list[Bar]) -> dict:
    """Convert a list of Bar objects to a plain-dict of parallel lists.

    Returns keys: open, high, low, close, ts, funding.
    Funding defaults to 0.0 when the bar has no funding rate.
    """
    return {
        "open": [b.open for b in bars],
        "high": [b.high for b in bars],
        "low": [b.low for b in bars],
        "close": [b.close for b in bars],
        "ts": [b.ts for b in bars],
        "funding": [b.funding if b.funding is not None else 0.0 for b in bars],
    }


def _summarize_bars(symbol: str, interval: str, bars: list[Bar]) -> dict:
    """Build the fetch_ohlcv summary dict from the fetched bars."""
    return {
        "symbol": symbol,
        "interval": interval,
        "n_bars": len(bars),
        "first_ts": bars[0].ts if bars else None,
        "last_ts": bars[-1].ts if bars else None,
        "closes": [b.close for b in bars],
    }


def fetch_ohlcv(
    symbol: str,
    interval: str,
    start_ms: int,
    end_ms: int,
    source: str = "binance",
    fetcher=None,
    root: str = "storage/parquet",
    progress=None,
) -> dict:
    """Fetch OHLCV bars and return a JSON-friendly summary dict.

    When ``fetcher`` is provided it is called directly (useful for testing and
    for injecting alternative data sources). Otherwise ``data.cache.get_bars``
    is used with the Binance fetcher.

    Returns a dict with: symbol, interval, n_bars, first_ts, last_ts, closes.
    """
    if fetcher is not None:
        bars = fetcher(symbol, interval, start_ms, end_ms, progress=progress)
    else:
        bars = get_bars(
            symbol, interval, start_ms, end_ms, root=root, progress=progress
        )
    return _summarize_bars(symbol, interval, bars)


# ---------------------------------------------------------------------------
# Task 2: run_sma_backtest
# ---------------------------------------------------------------------------


def run_sma_backtest(
    bars: list[Bar],
    fast: int,
    slow: int,
    *,
    taker_fee: float = 0.0,
    init_cash: float = 10_000.0,
) -> dict:
    """Run a single SMA-crossover backtest and return a JSON-friendly metrics dict.

    Uses the compiled fastsim kernel (fast_backtest) with signals generated by
    the vectorized SMA matrix + cross signal helpers.

    Returns a dict with: fast, slow, n_trades, total_return, win_rate,
    max_drawdown, profit_factor, sharpe, sortino, calmar, omega.
    """
    data = bars_to_data(bars)
    closes_arr = np.asarray(data["close"], dtype=float)

    smas = _sma_matrix(closes_arr, [fast, slow])
    entries, exits = _cross_signals(smas[fast], smas[slow])

    n = len(closes_arr)
    size = np.ones(n, dtype=float)
    side = np.ones(n, dtype=int)

    result = fast_backtest(
        data["open"], data["high"], data["low"], data["close"],
        data["funding"], data["ts"],
        entries, exits, size, side,
        taker_fee=taker_fee,
        init_cash=init_cash,
    )

    equity_curve = result["equity_curve"]
    trades = result["trades"]

    return {
        "fast": fast,
        "slow": slow,
        "n_trades": result["n_trades"],
        "total_return": _metrics.total_return(equity_curve),
        "win_rate": _metrics.win_rate(trades),
        "max_drawdown": _metrics.max_drawdown(equity_curve),
        "profit_factor": _metrics.profit_factor(trades),
        "sharpe": _metrics.sharpe(equity_curve),
        "sortino": _metrics.sortino(equity_curve),
        "calmar": _metrics.calmar(equity_curve),
        "omega": _metrics.omega(equity_curve),
    }


# ---------------------------------------------------------------------------
# Task 3: optimize_sma
# ---------------------------------------------------------------------------


def optimize_sma(
    bars: list[Bar],
    fasts: list[int],
    slows: list[int],
    *,
    fee_rate: float = 0.0,
    init_cash: float = 10_000.0,
    top_n: int = 5,
) -> dict:
    """Sweep an SMA(fast, slow) crossover grid and return ranked results.

    Uses ``sweep_sma_cross`` from the vectorized module (numba when available,
    numpy otherwise). Only combos where fast < slow are included.

    Returns a dict with: best (the top result dict), top (list of top_n dicts),
    n_combos (total combos evaluated).
    """
    data = bars_to_data(bars)
    closes_arr = np.asarray(data["close"], dtype=float)

    results = sweep_sma_cross(closes_arr, fasts, slows, fee_rate=fee_rate, init_cash=init_cash)

    # Filter to fast < slow only (valid combos)
    valid = [r for r in results if r["params"]["fast"] < r["params"]["slow"]]

    return {
        "best": valid[0] if valid else None,
        "top": valid[:top_n],
        "n_combos": len(valid),
    }


# ---------------------------------------------------------------------------
# Task 4: overfit_check
# ---------------------------------------------------------------------------


def overfit_check(
    trial_results: list[dict],
    n_obs: int,
    *,
    n_splits: int = 4,
) -> dict:
    """Compute overfitting statistics for a parameter sweep.

    ``trial_results`` is a list of dicts each with at least a ``sharpe`` key
    (as returned by run_sma_backtest or the sweep). ``n_obs`` is the number of
    bar observations in the backtest.

    Computes:
    - deflated_sharpe_ratio: P(best SR is real) after accounting for trials
    - pbo: Probability of Backtest Overfitting via CSCV
    - verdict: level + reasons from overfit_verdict

    Returns a dict with: deflated_sr, pbo, verdict_level, verdict_reasons.
    """
    if not trial_results:
        return {
            "deflated_sr": 0.0,
            "pbo": 0.0,
            "verdict_level": "High",
            "verdict_reasons": ["No trial results provided."],
        }

    sharpes = [r.get("sharpe", 0.0) for r in trial_results]
    observed_sr = max(sharpes)

    dsr = deflated_sharpe_ratio(observed_sr, sharpes, n_obs)

    # Build a matrix for pbo_cscv: n_obs rows x n_trials cols
    # We use per-bar return proxies: for simplicity, distribute total_return
    # evenly across observations for each trial.
    n_trials = len(trial_results)
    # matrix: list of n_obs lists of length n_trials
    # Use the per-trial sharpe scaled by 1/sqrt(n_obs) as a proxy per-bar return
    matrix = []
    for obs_idx in range(n_obs):
        row = [r.get("sharpe", 0.0) / max(n_obs, 1) for r in trial_results]
        matrix.append(row)

    # pbo_cscv requires n_splits even and n_obs >= n_splits
    effective_splits = n_splits if n_obs >= n_splits else 2
    # ensure even
    if effective_splits % 2 != 0:
        effective_splits = max(2, effective_splits - 1)

    try:
        pbo = pbo_cscv(matrix, effective_splits)
    except (ValueError, ZeroDivisionError):
        pbo = 0.0

    verdict = overfit_verdict(pbo, dsr)

    return {
        "deflated_sr": dsr,
        "pbo": pbo,
        "verdict_level": verdict.level,
        "verdict_reasons": verdict.reasons,
    }
